/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.DadosClientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Clientes;

/**
 *
 * @author Octavio
 */
public class Editar extends javax.swing.JFrame {

    DadosClientes dados = new DadosClientes();
    Clientes novoCliente;
    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    ArrayList<Clientes> cliente = new ArrayList();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_EditarCliente = new javax.swing.JPanel();
        label_nome2 = new javax.swing.JLabel();
        label_ID2 = new javax.swing.JLabel();
        label_CPF2 = new javax.swing.JLabel();
        label_RG2 = new javax.swing.JLabel();
        label_Endereco2 = new javax.swing.JLabel();
        label_Bairro2 = new javax.swing.JLabel();
        label_Cidade = new javax.swing.JLabel();
        label_CEP2 = new javax.swing.JLabel();
        box_UF2 = new javax.swing.JComboBox<>();
        label_UF2 = new javax.swing.JLabel();
        label_Telefone2 = new javax.swing.JLabel();
        label_Email2 = new javax.swing.JLabel();
        botao_Salvar = new javax.swing.JButton();
        label_Celular2 = new javax.swing.JLabel();
        label_Nascimento2 = new javax.swing.JLabel();
        campo_ID2 = new javax.swing.JFormattedTextField();
        campo_Nome2 = new javax.swing.JFormattedTextField();
        campo_CPF2 = new javax.swing.JFormattedTextField();
        campo_RG2 = new javax.swing.JFormattedTextField();
        campo_Cidade2 = new javax.swing.JFormattedTextField();
        campo_Endereco2 = new javax.swing.JFormattedTextField();
        campo_Bairro2 = new javax.swing.JFormattedTextField();
        campo_CEP2 = new javax.swing.JFormattedTextField();
        campo_Telefone2 = new javax.swing.JFormattedTextField();
        campo_Celular2 = new javax.swing.JFormattedTextField();
        campo_Nascimento2 = new javax.swing.JFormattedTextField();
        campo_Email2 = new javax.swing.JFormattedTextField();
        botao_Cancelar = new javax.swing.JButton();
        label_Editar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nome2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label_nome2.setText("Nome");

        label_ID2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label_ID2.setText("ID");

        label_CPF2.setText("CPF/CNPJ");

        label_RG2.setText("RG");

        label_Endereco2.setText("Endereço");

        label_Bairro2.setText("Bairro");

        label_Cidade.setText("Cidade");

        label_CEP2.setText("CEP");

        box_UF2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "AC\t ", "AL\t ", "AP\t ", "AM\t ", "BA\t ", "CE\t ", "DF\t ", "ES\t ", "GO\t ", "MA\t ", "MT\t ", "MS\t ", "MG\t ", "PA\t ", "PB\t ", "PR\t ", "PE\t ", "PI\t ", "RJ\t ", "RN\t ", "RS\t ", "RO\t ", "RR\t ", "SC\t ", "SP\t ", "SE\t ", "TO" }));
        box_UF2.setEnabled(false);
        box_UF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_UF2ActionPerformed(evt);
            }
        });

        label_UF2.setText("UF");

        label_Telefone2.setText("Telefone");

        label_Email2.setText("Email");

        botao_Salvar.setText("Salvar");
        botao_Salvar.setEnabled(false);
        botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_SalvarActionPerformed(evt);
            }
        });

        label_Celular2.setText("Celular");

        label_Nascimento2.setText("Nascimento");

        campo_ID2.setEditable(false);
        campo_ID2.setEnabled(false);

        campo_Nome2.setEditable(false);
        campo_Nome2.setEnabled(false);

        campo_CPF2.setEditable(false);
        try {
            campo_CPF2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_CPF2.setEnabled(false);

        campo_RG2.setEditable(false);
        campo_RG2.setEnabled(false);

        campo_Cidade2.setEditable(false);
        campo_Cidade2.setEnabled(false);

        campo_Endereco2.setEditable(false);
        campo_Endereco2.setEnabled(false);

        campo_Bairro2.setEditable(false);
        campo_Bairro2.setEnabled(false);

        campo_CEP2.setEditable(false);
        try {
            campo_CEP2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_CEP2.setEnabled(false);

        campo_Telefone2.setEditable(false);
        try {
            campo_Telefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Telefone2.setEnabled(false);
        campo_Telefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_Telefone2ActionPerformed(evt);
            }
        });

        campo_Celular2.setEditable(false);
        try {
            campo_Celular2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Celular2.setEnabled(false);

        try {
            campo_Nascimento2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Nascimento2.setEnabled(false);

        campo_Email2.setEditable(false);
        campo_Email2.setEnabled(false);

        botao_Cancelar.setText("Cancelar");
        botao_Cancelar.setEnabled(false);
        botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CancelarActionPerformed(evt);
            }
        });

        label_Editar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_Editar.setText("Editar Clientes");

        javax.swing.GroupLayout painel_EditarClienteLayout = new javax.swing.GroupLayout(painel_EditarCliente);
        painel_EditarCliente.setLayout(painel_EditarClienteLayout);
        painel_EditarClienteLayout.setHorizontalGroup(
            painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                    .addComponent(botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(botao_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                    .addComponent(label_ID2)
                                    .addGap(61, 61, 61)
                                    .addComponent(label_nome2)
                                    .addGap(194, 194, 194)
                                    .addComponent(label_CPF2)
                                    .addGap(101, 101, 101)
                                    .addComponent(label_RG2))
                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                    .addComponent(label_Endereco2)
                                    .addGap(252, 252, 252)
                                    .addComponent(label_Bairro2)
                                    .addGap(121, 121, 121)
                                    .addComponent(label_Cidade))
                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                    .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                            .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                                    .addComponent(label_Telefone2)
                                                    .addGap(119, 119, 119))
                                                .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                                    .addComponent(campo_Telefone2)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label_Celular2)
                                                .addComponent(campo_Celular2)))
                                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                            .addComponent(campo_CEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(box_UF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                            .addComponent(label_CEP2)
                                            .addGap(142, 142, 142)
                                            .addComponent(label_UF2))
                                        .addComponent(campo_Endereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label_Nascimento2)
                                                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(label_Email2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                                        .addComponent(campo_Bairro2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(17, 17, 17)
                                                        .addComponent(campo_Cidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(campo_Nascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(campo_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(campo_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(campo_Nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(campo_CPF2)
                            .addGap(18, 18, 18)
                            .addComponent(campo_RG2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(label_Editar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painel_EditarClienteLayout.setVerticalGroup(
            painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                .addComponent(label_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ID2)
                    .addComponent(label_nome2)
                    .addComponent(label_CPF2)
                    .addComponent(label_RG2))
                .addGap(6, 6, 6)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_Nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_CPF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_RG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Endereco2)
                    .addComponent(label_Bairro2)
                    .addComponent(label_Cidade))
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(campo_Cidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_Endereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_Bairro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_CEP2)
                    .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_UF2)
                        .addComponent(label_Nascimento2)))
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(box_UF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_CEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_EditarClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_Nascimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Telefone2)
                    .addComponent(label_Email2)
                    .addComponent(label_Celular2))
                .addGap(6, 6, 6)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Celular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(painel_EditarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painel_EditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_EditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CancelarActionPerformed
        campo_ID2.setText("");
        campo_Nome2.setText("");
        campo_CPF2.setText("");
        campo_RG2.setText("");
        campo_Endereco2.setText("");
        campo_Bairro2.setText("");
        campo_Cidade2.setText("");
        campo_CEP2.setText("");
        campo_Telefone2.setText("");
        campo_Celular2.setText("");
        campo_Email2.setText("");
        campo_Nascimento2.setText("");
        box_UF2.setSelectedIndex(0);

        campo_ID2.setEnabled(false);
        campo_Nome2.setEnabled(false);
        campo_CPF2.setEnabled(false);
        campo_RG2.setEnabled(false);
        campo_Endereco2.setEnabled(false);
        campo_Bairro2.setEnabled(false);
        campo_Cidade2.setEnabled(false);
        campo_CEP2.setEnabled(false);
        box_UF2.setEnabled(false);
        campo_Telefone2.setEnabled(false);
        campo_Celular2.setEnabled(false);
        campo_Email2.setEnabled(false);
        campo_Nascimento2.setEnabled(false);
        botao_Salvar.setEnabled(false);
        botao_Cancelar.setEnabled(false);
    }//GEN-LAST:event_botao_CancelarActionPerformed

    private void campo_Telefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_Telefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_Telefone2ActionPerformed

    private void botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_SalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!");

                    campo_ID2.setText("");
                    campo_Nome2.setText("");
                    campo_CPF2.setText("");
                    campo_RG2.setText("");
                    campo_Endereco2.setText("");
                    campo_Bairro2.setText("");
                    campo_Cidade2.setText("");
                    campo_CEP2.setText("");
                    campo_Telefone2.setText("");
                    campo_Celular2.setText("");
                    campo_Email2.setText("");
                    campo_Nascimento2.setText("");
                    box_UF2.setSelectedIndex(0);

                    campo_Nome2.setEnabled(false);
                    campo_CPF2.setEnabled(false);
                    campo_RG2.setEnabled(false);
                    campo_Endereco2.setEnabled(false);
                    campo_Bairro2.setEnabled(false);
                    campo_Cidade2.setEnabled(false);
                    campo_CEP2.setEnabled(false);
                    box_UF2.setEnabled(false);
                    campo_Telefone2.setEnabled(false);
                    campo_Celular2.setEnabled(false);
                    campo_Email2.setEnabled(false);
                    campo_Nascimento2.setEnabled(false);
                    botao_Salvar.setEnabled(false);
                    botao_Cancelar.setEnabled(false);
                }

                String id = campo_ID2.getText();
                String nome = campo_Nome2.getText();
                String cpf = campo_CPF2.getText();
                String rg = campo_RG2.getText();
                String endereco = campo_Endereco2.getText();
                String bairro = campo_Bairro2.getText();
                String cidade = campo_Cidade2.getText();
                String cep = campo_CEP2.getText();
                String telefone = campo_Telefone2.getText();
                String celular = campo_Celular2.getText();
                String email = campo_Email2.getText();
                String nascimento = campo_Nascimento2.getText();
                int UF = box_UF2.getSelectedIndex();

                Clientes c = new Clientes(id, nome, cpf, rg, endereco, bairro, cidade, cep, telefone, celular, email, nascimento, UF);
                dados.cadastaCliente(c);

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro"
                + erro.getMessage());
        }
    }//GEN-LAST:event_botao_SalvarActionPerformed

    private void box_UF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_UF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_UF2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Cancelar;
    private javax.swing.JButton botao_Salvar;
    private javax.swing.JComboBox<String> box_UF2;
    private javax.swing.JFormattedTextField campo_Bairro2;
    private javax.swing.JFormattedTextField campo_CEP2;
    private javax.swing.JFormattedTextField campo_CPF2;
    private javax.swing.JFormattedTextField campo_Celular2;
    private javax.swing.JFormattedTextField campo_Cidade2;
    private javax.swing.JFormattedTextField campo_Email2;
    private javax.swing.JFormattedTextField campo_Endereco2;
    private javax.swing.JFormattedTextField campo_ID2;
    private javax.swing.JFormattedTextField campo_Nascimento2;
    private javax.swing.JFormattedTextField campo_Nome2;
    private javax.swing.JFormattedTextField campo_RG2;
    private javax.swing.JFormattedTextField campo_Telefone2;
    private javax.swing.JLabel label_Bairro2;
    private javax.swing.JLabel label_CEP2;
    private javax.swing.JLabel label_CPF2;
    private javax.swing.JLabel label_Celular2;
    private javax.swing.JLabel label_Cidade;
    private javax.swing.JLabel label_Editar;
    private javax.swing.JLabel label_Email2;
    private javax.swing.JLabel label_Endereco2;
    private javax.swing.JLabel label_ID2;
    private javax.swing.JLabel label_Nascimento2;
    private javax.swing.JLabel label_RG2;
    private javax.swing.JLabel label_Telefone2;
    private javax.swing.JLabel label_UF2;
    private javax.swing.JLabel label_nome2;
    private javax.swing.JPanel painel_EditarCliente;
    // End of variables declaration//GEN-END:variables
private boolean validarCampos() {
        if (campo_Nome2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Nome Obrigatório");
            campo_Nome2.requestFocus();
            return false;
        }
        if (campo_CPF2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo CPF Obrigatório");
            campo_CPF2.requestFocus();
            return false;
        }
        if (campo_RG2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo RG Obrigatório");
            campo_RG2.requestFocus();
            return false;
        }
        if (campo_Endereco2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Endereco Obrigatório");
            campo_Endereco2.requestFocus();
            return false;
        }
        if (campo_Cidade2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Cidade Obrigatório");
            campo_Cidade2.requestFocus();
            return false;
        }
        if (campo_CEP2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo CEP Obrigatório");
            campo_CEP2.requestFocus();
            return false;
        }
        if (campo_Telefone2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Telefone Obrigatório");
            campo_Telefone2.requestFocus();
            return false;
        }
        if (campo_Nascimento2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Nascimento Obrigatório");
            campo_Nascimento2.requestFocus();
            return false;
        }
        if (box_UF2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "UF Obrigatório");
            box_UF2.requestFocus();
            return false;
        }

        return true;

    }

    private boolean preencherObjeto() throws Exception {
        novoCliente = new Clientes();
        novoCliente.setID(campo_Nome2.getText());
        novoCliente.setNome(campo_Nome2.getText());
        novoCliente.setCPF(campo_CPF2.getText());
        novoCliente.setRG(campo_RG2.getText());
        novoCliente.setEndereco(campo_Endereco2.getText());
        novoCliente.setBairro(campo_Bairro2.getText());
        novoCliente.setCidade(campo_Cidade2.getText());
        novoCliente.setCEP(campo_CEP2.getText());
        novoCliente.setTelefone(campo_Telefone2.getText());
        novoCliente.setCelular(campo_Celular2.getText());
        novoCliente.setEmail(campo_Email2.getText());
        novoCliente.setNascimento(campo_Nascimento2.getText());
        novoCliente.setUF(box_UF2.getSelectedIndex());

        return true;
    }

}



