/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.DadosClientes;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;

/**
 *
 * @author Octavio
 */
public class Principal extends javax.swing.JFrame {

    DadosClientes dados = new DadosClientes();
    Clientes novoCliente;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    ArrayList<Clientes> cliente = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        painel_Principal = new javax.swing.JTabbedPane();
        painel_NovoCliente = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        label_ID = new javax.swing.JLabel();
        label_CPF = new javax.swing.JLabel();
        label_RG = new javax.swing.JLabel();
        label_Endereco = new javax.swing.JLabel();
        label_Bairro = new javax.swing.JLabel();
        label_Cidade = new javax.swing.JLabel();
        label_CEP = new javax.swing.JLabel();
        box_UF = new javax.swing.JComboBox<>();
        label_UF = new javax.swing.JLabel();
        label_Telefone = new javax.swing.JLabel();
        label_Email = new javax.swing.JLabel();
        botao_Novo = new javax.swing.JButton();
        botao_Cancelar = new javax.swing.JButton();
        botao_Salvar = new javax.swing.JButton();
        label_Celular = new javax.swing.JLabel();
        botao_Sair = new javax.swing.JButton();
        label_Nascimento = new javax.swing.JLabel();
        campo_ID = new javax.swing.JFormattedTextField();
        campo_Nome = new javax.swing.JFormattedTextField();
        campo_CPF = new javax.swing.JFormattedTextField();
        campo_RG = new javax.swing.JFormattedTextField();
        campo_Cidade = new javax.swing.JFormattedTextField();
        campo_Endereco = new javax.swing.JFormattedTextField();
        campo_Bairro = new javax.swing.JFormattedTextField();
        campo_CEP = new javax.swing.JFormattedTextField();
        campo_Telefone = new javax.swing.JFormattedTextField();
        campo_Celular = new javax.swing.JFormattedTextField();
        campo_Nascimento = new javax.swing.JFormattedTextField();
        campo_Email = new javax.swing.JFormattedTextField();
        painel_VisualizarClientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_ListaDeClientes = new javax.swing.JTable();
        botao_Editar = new javax.swing.JButton();
        botao_Excluir = new javax.swing.JButton();
        painel_Ajuda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(null);

        painel_Principal.setBackground(java.awt.Color.white);
        painel_Principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label_nome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label_nome.setText("Nome");

        label_ID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        label_ID.setText("ID");

        label_CPF.setText("CPF/CNPJ");

        label_RG.setText("RG");

        label_Endereco.setText("Endereço");

        label_Bairro.setText("Bairro");

        label_Cidade.setText("Cidade");

        label_CEP.setText("CEP");

        box_UF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "AC\t ", "AL\t ", "AP\t ", "AM\t ", "BA\t ", "CE\t ", "DF\t ", "ES\t ", "GO\t ", "MA\t ", "MT\t ", "MS\t ", "MG\t ", "PA\t ", "PB\t ", "PR\t ", "PE\t ", "PI\t ", "RJ\t ", "RN\t ", "RS\t ", "RO\t ", "RR\t ", "SC\t ", "SP\t ", "SE\t ", "TO" }));
        box_UF.setEnabled(false);
        box_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_UFActionPerformed(evt);
            }
        });

        label_UF.setText("UF");

        label_Telefone.setText("Telefone");

        label_Email.setText("Email");

        botao_Novo.setText("Novo");
        botao_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_NovoActionPerformed(evt);
            }
        });

        botao_Cancelar.setText("Cancelar");
        botao_Cancelar.setEnabled(false);
        botao_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CancelarActionPerformed(evt);
            }
        });

        botao_Salvar.setText("Salvar");
        botao_Salvar.setEnabled(false);
        botao_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_SalvarActionPerformed(evt);
            }
        });

        label_Celular.setText("Celular");

        botao_Sair.setText("Sair");
        botao_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_SairActionPerformed(evt);
            }
        });

        label_Nascimento.setText("Nascimento");

        campo_ID.setEditable(false);
        campo_ID.setEnabled(false);

        campo_Nome.setEditable(false);
        campo_Nome.setEnabled(false);

        campo_CPF.setEditable(false);
        try {
            campo_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_CPF.setEnabled(false);

        campo_RG.setEditable(false);
        campo_RG.setEnabled(false);

        campo_Cidade.setEditable(false);
        campo_Cidade.setEnabled(false);

        campo_Endereco.setEditable(false);
        campo_Endereco.setEnabled(false);

        campo_Bairro.setEditable(false);
        campo_Bairro.setEnabled(false);

        campo_CEP.setEditable(false);
        try {
            campo_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_CEP.setEnabled(false);

        campo_Telefone.setEditable(false);
        try {
            campo_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Telefone.setEnabled(false);
        campo_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_TelefoneActionPerformed(evt);
            }
        });

        campo_Celular.setEditable(false);
        try {
            campo_Celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Celular.setEnabled(false);

        try {
            campo_Nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_Nascimento.setEnabled(false);

        campo_Email.setEditable(false);
        campo_Email.setEnabled(false);

        javax.swing.GroupLayout painel_NovoClienteLayout = new javax.swing.GroupLayout(painel_NovoCliente);
        painel_NovoCliente.setLayout(painel_NovoClienteLayout);
        painel_NovoClienteLayout.setHorizontalGroup(
            painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                .addComponent(botao_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                .addComponent(label_ID)
                                .addGap(61, 61, 61)
                                .addComponent(label_nome)
                                .addGap(194, 194, 194)
                                .addComponent(label_CPF)
                                .addGap(101, 101, 101)
                                .addComponent(label_RG))
                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                .addComponent(label_Endereco)
                                .addGap(252, 252, 252)
                                .addComponent(label_Bairro)
                                .addGap(121, 121, 121)
                                .addComponent(label_Cidade))
                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                        .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                                .addComponent(label_Telefone)
                                                .addGap(119, 119, 119))
                                            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                                .addComponent(campo_Telefone)
                                                .addGap(18, 18, 18)))
                                        .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_Celular)
                                            .addComponent(campo_Celular)))
                                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                        .addComponent(campo_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                        .addComponent(label_CEP)
                                        .addGap(142, 142, 142)
                                        .addComponent(label_UF))
                                    .addComponent(campo_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_Nascimento)
                                            .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(label_Email, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                                    .addComponent(campo_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(17, 17, 17)
                                                    .addComponent(campo_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(campo_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(campo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_CPF)
                        .addGap(18, 18, 18)
                        .addComponent(campo_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        painel_NovoClienteLayout.setVerticalGroup(
            painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ID)
                    .addComponent(label_nome)
                    .addComponent(label_CPF)
                    .addComponent(label_RG))
                .addGap(6, 6, 6)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Endereco)
                    .addComponent(label_Bairro)
                    .addComponent(label_Cidade))
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(campo_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_CEP)
                    .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_UF)
                        .addComponent(label_Nascimento)))
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(box_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_NovoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Telefone)
                    .addComponent(label_Email)
                    .addComponent(label_Celular))
                .addGap(6, 6, 6)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(painel_NovoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        painel_Principal.addTab("Novo Cliente", painel_NovoCliente);

        Tabela_ListaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabela_ListaDeClientes);

        botao_Editar.setText("Editar");
        botao_Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_EditarMouseClicked(evt);
            }
        });
        botao_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_EditarActionPerformed(evt);
            }
        });

        botao_Excluir.setText("Excluir");
        botao_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_VisualizarClientesLayout = new javax.swing.GroupLayout(painel_VisualizarClientes);
        painel_VisualizarClientes.setLayout(painel_VisualizarClientesLayout);
        painel_VisualizarClientesLayout.setHorizontalGroup(
            painel_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(painel_VisualizarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painel_VisualizarClientesLayout.setVerticalGroup(
            painel_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_VisualizarClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_VisualizarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(botao_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        painel_Principal.addTab("Visualizar Clientes", painel_VisualizarClientes);

        painel_Ajuda.setLayout(null);
        painel_Principal.addTab("Ajuda", painel_Ajuda);

        getContentPane().add(painel_Principal);
        painel_Principal.setBounds(18, 27, 620, 370);

        setSize(new java.awt.Dimension(670, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_SalvarActionPerformed
        DefaultTableModel dtmClientes = (DefaultTableModel) Tabela_ListaDeClientes.getModel();
        Object[] exibirDados = {campo_ID.getText(), campo_Nome.getText(), campo_CPF.getText(), campo_Celular.getText()};
        dtmClientes.addRow(exibirDados);

        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!");

                    campo_ID.setText("");
                    campo_Nome.setText("");
                    campo_CPF.setText("");
                    campo_RG.setText("");
                    campo_Endereco.setText("");
                    campo_Bairro.setText("");
                    campo_Cidade.setText("");
                    campo_CEP.setText("");
                    campo_Telefone.setText("");
                    campo_Celular.setText("");
                    campo_Email.setText("");
                    campo_Nascimento.setText("");
                    box_UF.setSelectedIndex(0);

                    campo_Nome.setEnabled(false);
                    campo_CPF.setEnabled(false);
                    campo_RG.setEnabled(false);
                    campo_Endereco.setEnabled(false);
                    campo_Bairro.setEnabled(false);
                    campo_Cidade.setEnabled(false);
                    campo_CEP.setEnabled(false);
                    box_UF.setEnabled(false);
                    campo_Telefone.setEnabled(false);
                    campo_Celular.setEnabled(false);
                    campo_Email.setEnabled(false);
                    campo_Nascimento.setEnabled(false);
                    botao_Salvar.setEnabled(false);
                    botao_Cancelar.setEnabled(false);
                }

                String id = campo_ID.getText();
                String nome = campo_Nome.getText();
                String cpf = campo_CPF.getText();
                String rg = campo_RG.getText();
                String endereco = campo_Endereco.getText();
                String bairro = campo_Bairro.getText();
                String cidade = campo_Cidade.getText();
                String cep = campo_CEP.getText();
                String telefone = campo_Telefone.getText();
                String celular = campo_Celular.getText();
                String email = campo_Email.getText();
                String nascimento = campo_Nascimento.getText();
                int UF = box_UF.getSelectedIndex();

                Clientes c = new Clientes(id, nome, cpf, rg, endereco, bairro, cidade, cep, telefone, celular, email, nascimento, UF);
                dados.cadastaCliente(c);

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro"
                    + erro.getMessage());
        }

    }//GEN-LAST:event_botao_SalvarActionPerformed

    private void botao_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CancelarActionPerformed
        campo_ID.setText("");
        campo_Nome.setText("");
        campo_CPF.setText("");
        campo_RG.setText("");
        campo_Endereco.setText("");
        campo_Bairro.setText("");
        campo_Cidade.setText("");
        campo_CEP.setText("");
        campo_Telefone.setText("");
        campo_Celular.setText("");
        campo_Email.setText("");
        campo_Nascimento.setText("");
        box_UF.setSelectedIndex(0);

        campo_ID.setEnabled(false);
        campo_Nome.setEnabled(false);
        campo_CPF.setEnabled(false);
        campo_RG.setEnabled(false);
        campo_Endereco.setEnabled(false);
        campo_Bairro.setEnabled(false);
        campo_Cidade.setEnabled(false);
        campo_CEP.setEnabled(false);
        box_UF.setEnabled(false);
        campo_Telefone.setEnabled(false);
        campo_Celular.setEnabled(false);
        campo_Email.setEnabled(false);
        campo_Nascimento.setEnabled(false);
        botao_Salvar.setEnabled(false);
        botao_Cancelar.setEnabled(false);

    }//GEN-LAST:event_botao_CancelarActionPerformed

    private void botao_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_NovoActionPerformed

        campo_Nome.setEnabled(true);
        campo_Nome.setEditable(true);
        campo_CPF.setEnabled(true);
        campo_CPF.setEditable(true);
        campo_RG.setEnabled(true);
        campo_RG.setEditable(true);
        campo_Endereco.setEnabled(true);
        campo_Endereco.setEditable(true);
        campo_Bairro.setEnabled(true);
        campo_Bairro.setEditable(true);
        campo_Cidade.setEnabled(true);
        campo_Cidade.setEditable(true);
        campo_CEP.setEnabled(true);
        campo_CEP.setEditable(true);
        box_UF.setEnabled(true);
        campo_Telefone.setEnabled(true);
        campo_Telefone.setEditable(true);
        campo_Celular.setEnabled(true);
        campo_Celular.setEditable(true);
        campo_Email.setEnabled(true);
        campo_Email.setEditable(true);
        campo_Nascimento.setEnabled(true);
        campo_Nascimento.setEditable(true);               
        botao_Salvar.setEnabled(true);
        botao_Cancelar.setEnabled(true);
        
    }//GEN-LAST:event_botao_NovoActionPerformed

    private void box_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_UFActionPerformed

    private void botao_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botao_SairActionPerformed

    private void botao_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_EditarActionPerformed
   
              
    }//GEN-LAST:event_botao_EditarActionPerformed

    private void botao_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ExcluirActionPerformed

        if (Tabela_ListaDeClientes.getSelectedRow() != -1) {

            DefaultTableModel dtmClientes = (DefaultTableModel) Tabela_ListaDeClientes.getModel();
            dtmClientes.removeRow(Tabela_ListaDeClientes.getSelectedRow());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir!");
        }
    }//GEN-LAST:event_botao_ExcluirActionPerformed

    private void botao_EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_EditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_EditarMouseClicked

    private void campo_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_TelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_ListaDeClientes;
    private javax.swing.JButton botao_Cancelar;
    private javax.swing.JButton botao_Editar;
    private javax.swing.JButton botao_Excluir;
    private javax.swing.JButton botao_Novo;
    private javax.swing.JButton botao_Sair;
    private javax.swing.JButton botao_Salvar;
    private javax.swing.JComboBox<String> box_UF;
    private javax.swing.JFormattedTextField campo_Bairro;
    private javax.swing.JFormattedTextField campo_CEP;
    private javax.swing.JFormattedTextField campo_CPF;
    private javax.swing.JFormattedTextField campo_Celular;
    private javax.swing.JFormattedTextField campo_Cidade;
    private javax.swing.JFormattedTextField campo_Email;
    private javax.swing.JFormattedTextField campo_Endereco;
    private javax.swing.JFormattedTextField campo_ID;
    private javax.swing.JFormattedTextField campo_Nascimento;
    private javax.swing.JFormattedTextField campo_Nome;
    private javax.swing.JFormattedTextField campo_RG;
    private javax.swing.JFormattedTextField campo_Telefone;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_Bairro;
    private javax.swing.JLabel label_CEP;
    private javax.swing.JLabel label_CPF;
    private javax.swing.JLabel label_Celular;
    private javax.swing.JLabel label_Cidade;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Endereco;
    private javax.swing.JLabel label_ID;
    private javax.swing.JLabel label_Nascimento;
    private javax.swing.JLabel label_RG;
    private javax.swing.JLabel label_Telefone;
    private javax.swing.JLabel label_UF;
    private javax.swing.JLabel label_nome;
    private javax.swing.JPanel painel_Ajuda;
    private javax.swing.JPanel painel_NovoCliente;
    private javax.swing.JTabbedPane painel_Principal;
    private javax.swing.JPanel painel_VisualizarClientes;
    // End of variables declaration//GEN-END:variables
private boolean validarCampos() {
        if (campo_Nome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Nome Obrigatório");
            campo_Nome.requestFocus();
            return false;
        }
        if (campo_CPF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo CPF Obrigatório");
            campo_CPF.requestFocus();
            return false;
        }
        if (campo_RG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo RG Obrigatório");
            campo_RG.requestFocus();
            return false;
        }
        if (campo_Endereco.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Endereco Obrigatório");
            campo_Endereco.requestFocus();
            return false;
        }
        if (campo_Cidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Cidade Obrigatório");
            campo_Cidade.requestFocus();
            return false;
        }
        if (campo_CEP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo CEP Obrigatório");
            campo_CEP.requestFocus();
            return false;
        }
        if (campo_Telefone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Telefone Obrigatório");
            campo_Telefone.requestFocus();
            return false;
        }
        if (campo_Nascimento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Nascimento Obrigatório");
            campo_Nascimento.requestFocus();
            return false;
        }
        if (box_UF.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "UF Obrigatório");
            box_UF.requestFocus();
            return false;
        }

        return true;

    }

    private boolean preencherObjeto() throws Exception {
        novoCliente = new Clientes();
        novoCliente.setID(campo_Nome.getText());
        novoCliente.setNome(campo_Nome.getText());
        novoCliente.setCPF(campo_CPF.getText());
        novoCliente.setRG(campo_RG.getText());
        novoCliente.setEndereco(campo_Endereco.getText());
        novoCliente.setBairro(campo_Bairro.getText());
        novoCliente.setCidade(campo_Cidade.getText());
        novoCliente.setCEP(campo_CEP.getText());
        novoCliente.setTelefone(campo_Telefone.getText());
        novoCliente.setCelular(campo_Celular.getText());
        novoCliente.setEmail(campo_Email.getText());
        novoCliente.setNascimento(campo_Nascimento.getText());
        novoCliente.setUF(box_UF.getSelectedIndex());

        return true;
    }

}
